[2020-03-20 18:54:59 log.py:30 CRITICAL           initialize()] Logging initialised, level=20
[2020-03-20 18:56:41 log.py:30 CRITICAL           initialize()] Logging initialised, level=20
[2020-03-20 19:00:26 log.py:30 CRITICAL           initialize()] Logging initialised, level=20
[2020-03-20 19:03:18 log.py:30 CRITICAL           initialize()] Logging initialised, level=20
[2020-03-20 19:03:23 _internal.py:113 INFO                 _log()]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2020-03-20 19:03:57 _internal.py:113 INFO                 _log()] 127.0.0.1 - - [20/Mar/2020 19:03:57] "[33mGET / HTTP/1.1[0m" 404 -
[2020-03-20 19:04:23 log.py:30 CRITICAL           initialize()] Logging initialised, level=20
[2020-03-20 19:04:27 _internal.py:113 INFO                 _log()]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2020-03-20 19:05:41 _internal.py:113 INFO                 _log()] 127.0.0.1 - - [20/Mar/2020 19:05:41] "[33mGET / HTTP/1.1[0m" 404 -
[2020-03-20 19:06:05 app.py:17 INFO                index()] > MS_SQL data request
[2020-03-20 19:06:06 ms_sql.py:49 ERROR       get_table_data()] NEO_MAR_15.masterss.tbl_countries error: ('42S02', "[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'NEO_MAR_15.masterss.tbl_countries'. (208) (SQLExecDirectW)")
[2020-03-20 19:06:07 app.py:24 INFO                index()] < SqlServerApi --> {'status': 200, 'data': {'NEO_MAR_15.masters.tbl_block': [{'block_id': 1, 'block_name': 'Block A', 'created_by': 1, 'created_on': datetime.datetime(2020, 3, 6, 15, 7, 18, 113000), 'is_active': True, '
[2020-03-20 19:06:07 _internal.py:113 INFO                 _log()] 127.0.0.1 - - [20/Mar/2020 19:06:07] "[37mGET /SqlServerApi HTTP/1.1[0m" 200 -
[2020-03-21 11:38:40 log.py:30 CRITICAL           initialize()] Logging initialised, level=20
[2020-03-21 11:38:40 _internal.py:113 INFO                 _log()]  * Restarting with stat
[2020-03-21 11:38:41 log.py:30 CRITICAL           initialize()] Logging initialised, level=20
[2020-03-21 11:38:41 _internal.py:113 WARNING                 _log()]  * Debugger is active!
[2020-03-21 11:38:41 _internal.py:113 INFO                 _log()]  * Debugger PIN: 334-425-192
[2020-03-21 11:38:41 _internal.py:113 INFO                 _log()]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2020-03-21 11:38:59 app.py:4144 INFO                  get()] > MS_SQL data request
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_block error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_bu error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_category_type error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_center error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_center_category error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_center_type error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_cluster error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_contract error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_contract_stages error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masterss.tbl_countries error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_courses error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_customer error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_customer_address error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_customer_group error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_customer_spoc error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_districts error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_entity error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_funding_source error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_industry_type error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_practice error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_product error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_project_group error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_project_type error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_projects error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_qp error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_question_type error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_region error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_sales_category error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_sector error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_states error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_sub_center error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_sub_projects error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_target_type error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_tma_candidate_attendance error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.masters.tbl_tma_trainer_stage_log error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.users.tbl_users error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.users.tbl_user_details error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 ms_sql.py:44 ERROR       get_table_data()] NEO_MAR_15.users.tbl_map_user_employee_department error: 'Row' object has no attribute 'column_name'
[2020-03-21 11:39:00 app.py:4151 INFO                  get()] < SqlServerApi --> {'status': 200, 'data': {'NEO_MAR_15.masters.tbl_block': "'Row' object has no attribute 'column_name'", 'NEO_MAR_15.masters.tbl_bu': "'Row' object has no attribute 'column_name'", 'NEO_MAR_15.masters.
[2020-03-21 11:39:00 _internal.py:113 INFO                 _log()] 127.0.0.1 - - [21/Mar/2020 11:39:00] "[37mGET /SqlServerApi HTTP/1.1[0m" 200 -
[2020-03-21 11:40:45 _internal.py:113 INFO                 _log()]  * Detected change in 'C:\\Users\\Jagdish P K\\Desktop\\APP\\code\\neo-web\\lib\\ms_sql.py', reloading
[2020-03-21 11:40:45 _internal.py:113 INFO                 _log()]  * Restarting with stat
[2020-03-21 11:40:46 log.py:30 CRITICAL           initialize()] Logging initialised, level=20
[2020-03-21 11:40:46 _internal.py:113 WARNING                 _log()]  * Debugger is active!
[2020-03-21 11:40:46 _internal.py:113 INFO                 _log()]  * Debugger PIN: 334-425-192
[2020-03-21 11:40:46 _internal.py:113 INFO                 _log()]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2020-03-21 11:40:51 log.py:30 CRITICAL           initialize()] Logging initialised, level=20
[2020-03-21 11:40:51 _internal.py:113 INFO                 _log()]  * Restarting with stat
[2020-03-21 11:40:52 log.py:30 CRITICAL           initialize()] Logging initialised, level=20
[2020-03-21 11:40:52 _internal.py:113 WARNING                 _log()]  * Debugger is active!
[2020-03-21 11:40:52 _internal.py:113 INFO                 _log()]  * Debugger PIN: 334-425-192
[2020-03-21 11:40:52 _internal.py:113 INFO                 _log()]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2020-03-21 11:40:58 app.py:4144 INFO                  get()] > MS_SQL data request
[2020-03-21 11:40:59 ms_sql.py:45 ERROR       get_table_data()] NEO_MAR_15.masterss.tbl_countries error: ('42S02', "[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'NEO_MAR_15.masterss.tbl_countries'. (208) (SQLExecDirectW)")
[2020-03-21 11:40:59 app.py:4151 INFO                  get()] < SqlServerApi --> {'status': 200, 'data': {'NEO_MAR_15.masters.tbl_block': [{'block_id': 1, 'block_name': 'Block A', 'created_by': 1, 'created_on': datetime.datetime(2020, 3, 6, 15, 7, 18, 113000), 'is_active': True, '
[2020-03-21 11:40:59 _internal.py:113 INFO                 _log()] 127.0.0.1 - - [21/Mar/2020 11:40:59] "[37mGET /SqlServerApi HTTP/1.1[0m" 200 -
